#!/bin/sh
rsync -av ./ algerib5@162.241.252.158:~/public_html/main  --exclude-from=.gitignore --exclude=".*"  --exclude=.env --exclude=public
ssh algerib5@162.241.252.158 'cd ~/public_html/main && php bin/console cache:clear'