<?php

namespace ContainerMVIXmUm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gl42ay7Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Gl42ay7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gl42ay7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'booking' => ['privates', '.errored..service_locator.Gl42ay7.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.Gl42ay7": it references class "App\\Entity\\Booking" but no such service exists.'],
        ], [
            'booking' => 'App\\Entity\\Booking',
        ]);
    }
}
