<?php

namespace ContainerMVIXmUm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAmbassadorRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AmbassadorRepository' shared autowired service.
     *
     * @return \App\Repository\AmbassadorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AmbassadorRepository'] = new \App\Repository\AmbassadorRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
