<?php

namespace ContainerMVIXmUm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingWithAmbassadorRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BookingWithAmbassadorRepository' shared autowired service.
     *
     * @return \App\Repository\BookingWithAmbassadorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BookingWithAmbassadorRepository'] = new \App\Repository\BookingWithAmbassadorRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
