<?php

namespace ContainerMVIXmUm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Gl42ay7.App\Entity\Booking' shared service.
     *
     * @return \App\Entity\Booking
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Gl42ay7": it references class "App\\Entity\\Booking" but no such service exists.');
    }
}
