<?php

namespace ContainerMVIXmUm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCitizenRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CitizenRepository' shared autowired service.
     *
     * @return \App\Repository\CitizenRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CitizenRepository'] = new \App\Repository\CitizenRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
