<?php

namespace ContainerMVIXmUm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'CalendarBundle\Controller\CalendarController' shared autowired service.
     *
     * @return \CalendarBundle\Controller\CalendarController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['CalendarBundle\\Controller\\CalendarController'] = new \CalendarBundle\Controller\CalendarController(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), new \CalendarBundle\Serializer\Serializer());
    }
}
