<?php

namespace ContainerU00CKmh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NKNbVZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.n_kNbVZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n_kNbVZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\BookingWithAmbassadorRepository', 'getBookingWithAmbassadorRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\BookingWithAmbassadorRepository',
        ]);
    }
}
