<?php

namespace ContainerU00CKmh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingWithAmbassadorTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\BookingWithAmbassadorType' shared autowired service.
     *
     * @return \App\Form\BookingWithAmbassadorType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\BookingWithAmbassadorType'] = new \App\Form\BookingWithAmbassadorType();
    }
}
