<?php

namespace ContainerU00CKmh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventSubscriber\CalendarSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\CalendarSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventSubscriber\\CalendarSubscriber'] = new \App\EventSubscriber\CalendarSubscriber(($container->privates['App\\Repository\\BookingRepository'] ?? $container->load('getBookingRepositoryService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
