<?php

namespace ContainerU00CKmh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Dbal_DefaultConnectionService extends App_KernelProdContainer
{
    /*
     * Gets the public 'doctrine.dbal.default_connection' shared service.
     *
     * @return \Doctrine\DBAL\Connection
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine.orm.default_listeners.attach_entity_listeners' => ['privates', 'doctrine.orm.default_listeners.attach_entity_listeners', 'getDoctrine_Orm_DefaultListeners_AttachEntityListenersService', true],
            'doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber' => ['privates', 'doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber', 'getDoctrine_Orm_Listeners_PdoCacheAdapterDoctrineSchemaSubscriberService', true],
            'vich_uploader.listener.clean.article_image' => ['privates', 'vich_uploader.listener.clean.article_image', 'getVichUploader_Listener_Clean_ArticleImageService', true],
            'vich_uploader.listener.clean.document_file' => ['privates', 'vich_uploader.listener.clean.document_file', 'getVichUploader_Listener_Clean_DocumentFileService', true],
            'vich_uploader.listener.clean.popup_image' => ['privates', 'vich_uploader.listener.clean.popup_image', 'getVichUploader_Listener_Clean_PopupImageService', true],
            'vich_uploader.listener.remove.article_image' => ['privates', 'vich_uploader.listener.remove.article_image', 'getVichUploader_Listener_Remove_ArticleImageService', true],
            'vich_uploader.listener.remove.document_file' => ['privates', 'vich_uploader.listener.remove.document_file', 'getVichUploader_Listener_Remove_DocumentFileService', true],
            'vich_uploader.listener.remove.popup_image' => ['privates', 'vich_uploader.listener.remove.popup_image', 'getVichUploader_Listener_Remove_PopupImageService', true],
            'vich_uploader.listener.upload.article_image' => ['privates', 'vich_uploader.listener.upload.article_image', 'getVichUploader_Listener_Upload_ArticleImageService', true],
            'vich_uploader.listener.upload.document_file' => ['privates', 'vich_uploader.listener.upload.document_file', 'getVichUploader_Listener_Upload_DocumentFileService', true],
            'vich_uploader.listener.upload.popup_image' => ['privates', 'vich_uploader.listener.upload.popup_image', 'getVichUploader_Listener_Upload_PopupImageService', true],
        ], [
            'doctrine.orm.default_listeners.attach_entity_listeners' => '?',
            'doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber' => '?',
            'vich_uploader.listener.clean.article_image' => '?',
            'vich_uploader.listener.clean.document_file' => '?',
            'vich_uploader.listener.clean.popup_image' => '?',
            'vich_uploader.listener.remove.article_image' => '?',
            'vich_uploader.listener.remove.document_file' => '?',
            'vich_uploader.listener.remove.popup_image' => '?',
            'vich_uploader.listener.upload.article_image' => '?',
            'vich_uploader.listener.upload.document_file' => '?',
            'vich_uploader.listener.upload.popup_image' => '?',
        ]), [0 => 'vich_uploader.listener.clean.article_image', 1 => 'vich_uploader.listener.clean.popup_image', 2 => 'vich_uploader.listener.clean.document_file', 3 => 'doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber', 4 => 'vich_uploader.listener.remove.article_image', 5 => 'vich_uploader.listener.upload.article_image', 6 => 'vich_uploader.listener.remove.popup_image', 7 => 'vich_uploader.listener.upload.popup_image', 8 => 'vich_uploader.listener.remove.document_file', 9 => 'vich_uploader.listener.upload.document_file']);
        $a->addEventListener([0 => 'loadClassMetadata'], 'doctrine.orm.default_listeners.attach_entity_listeners');

        return $container->services['doctrine.dbal.default_connection'] = (new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory([]))->createConnection(['connection_override_options' => [], 'url' => $container->getEnv('resolve:DATABASE_URL'), 'driver' => 'pdo_mysql', 'host' => 'localhost', 'port' => NULL, 'user' => 'root', 'password' => NULL, 'driverOptions' => [], 'defaultTableOptions' => []], new \Doctrine\DBAL\Configuration(), $a, []);
    }
}
