<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMVIXmUm\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMVIXmUm/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMVIXmUm.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMVIXmUm\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerMVIXmUm\App_KernelProdContainer([
    'container.build_hash' => 'MVIXmUm',
    'container.build_id' => '2b3462d7',
    'container.build_time' => 1660401678,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMVIXmUm');
