easy_admin:
  entities:
    Article:
      class: App\Entity\Article
      list:
        fields: ['id', 'title', 'published_at']
        actions: ['new', 'edit', '-delete']
      edit:
        actions: ['-delete', '-edit']
      form:
        fields:
          - {property: 'title'}
          - {property: 'description', label: 'The Description'}
          - {property: 'published_at', label: 'Published At', type_options: {'widget': 'single_text', 'attr': {'class': 'datepicker'}} }
          - {property: 'imageFile', type: 'vich_image'}
