<?php

namespace ContainerKFLVa3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LN3uI1AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LN3uI1A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LN3uI1A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\DocumentRepository',
        ]);
    }
}
