<?php

namespace ContainerKFLVa3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAmbassadorRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\AmbassadorRepository' shared autowired service.
     *
     * @return \App\Repository\AmbassadorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/AmbassadorRepository.php';

        return $container->privates['App\\Repository\\AmbassadorRepository'] = new \App\Repository\AmbassadorRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
