<?php

namespace ContainerKFLVa3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchedulerRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SchedulerRepository' shared autowired service.
     *
     * @return \App\Repository\SchedulerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/SchedulerRepository.php';

        return $container->privates['App\\Repository\\SchedulerRepository'] = new \App\Repository\SchedulerRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
