<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFLVa3j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFLVa3j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKFLVa3j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKFLVa3j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKFLVa3j\App_KernelDevDebugContainer([
    'container.build_hash' => 'KFLVa3j',
    'container.build_id' => '45217cac',
    'container.build_time' => 1660401663,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFLVa3j');
