<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \App\Entity\Article implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'titleEn', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'descriptionEn', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'titleFr', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'descriptionFr', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'fileName', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'published_at', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'CreatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'titleEn', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'descriptionEn', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'titleFr', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'descriptionFr', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'fileName', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'published_at', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'CreatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Article $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleEn', []);

        return parent::getTitleEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleEn($titleEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleEn', [$titleEn]);

        return parent::setTitleEn($titleEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionEn', []);

        return parent::getDescriptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionEn($descriptionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionEn', [$descriptionEn]);

        return parent::setDescriptionEn($descriptionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleFr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleFr', []);

        return parent::getTitleFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleFr($titleFr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleFr', [$titleFr]);

        return parent::setTitleFr($titleFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionFr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionFr', []);

        return parent::getDescriptionFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionFr($descriptionFr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionFr', [$descriptionFr]);

        return parent::setDescriptionFr($descriptionFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileName', []);

        return parent::getFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileName(?string $fileName): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileName', [$fileName]);

        return parent::setFileName($fileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $imageFile): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$imageFile]);

        parent::setImageFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishedAt', []);

        return parent::getPublishedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getStringPublishedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStringPublishedAt', []);

        return parent::getStringPublishedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishedAt(\DateTimeInterface $published_at): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishedAt', [$published_at]);

        return parent::setPublishedAt($published_at);
    }

}
